---
  - name: Installing and Launch Filebeat
    hosts: webservers
    become: true 
    tasks:
      # Grab the filebeat .deb file
    - name: Download my Filebeats
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install the downloaded file (filebeat)
      command: dpkg -i filebeat-7.6.1-amd64.deb


    - name: Copy in the filebeat.yml into Ansible config
      copy: 
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml


    - name: Enable and Configure System Module
      command: filebeat modules enable system


    - name: Run Filebeat on destination 
      command: filebeat setup
      

    - name: Start Filebeat Services
      command: systemctl start filebeat

    - name: Enable Filebeat at Boot up
      systemd:
        name: filebeat
        enabled: yes

