---
  - name: Installing and Launch Metricbeat
    hosts: webservers
    become: true 
    tasks:
      # Grab the metricbeat .deb file
    - name: Download my metricbeats
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: Install the downloaded file (filebeat)
      command: dpkg -i metricbeat-7.4.0-amd64.deb


    - name: Copy in the metricbeat.yml into Ansible config
      copy: 
        src: /etc/ansible/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml


    - name: Enable and Configure Docker Module
      command: metricbeat modules enable docker


    - name: Run metricbeat on destination 
      command: metricbeat setup
      

    - name: Start metricbeat Services
      command: systemctl start metricbeat

    - name: Enable Filebeat at Boot up
      systemd:
        name: metricbeat
        enabled: yes

